-- Create journal_entries table
create table journal_entries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  content text not null,
  is_ai_enabled boolean default false,
  
  -- AI Analysis Columns (Nullable for Private entries)
  sentiment_score int,          -- 0 to 100
  mood_tags text[],            -- Array of keywords
  ai_summary text,             -- Brief summary or response
  
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table journal_entries enable row level security;

-- Policies
create policy "Users can view own journal entries" on journal_entries for select using (auth.uid() = user_id);
create policy "Users can insert own journal entries" on journal_entries for insert with check (auth.uid() = user_id);
create policy "Users can update own journal entries" on journal_entries for update using (auth.uid() = user_id);
create policy "Users can delete own journal entries" on journal_entries for delete using (auth.uid() = user_id);
