-- ==========================================
-- MINDEASE MASTER SCHEMA - PRODUCTION READY
-- ==========================================
-- Run this script in your Supabase SQL Editor to set up the entire database.

-- 1. EXTENSIONS
create extension if not exists "uuid-ossp";

-- 2. TABLES

-- PROFILES
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  name text,
  streak_count int default 0,
  last_check_in timestamp with time zone,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- JOURNAL ENTRIES (Consolidated)
create table if not exists public.journal_entries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  content text,
  mood_level int check (mood_level between 1 and 5),
  is_ai_enabled boolean default false,
  sentiment_score int,
  mood_tags text[],
  ai_summary text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- CHATS
create table if not exists public.chats (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  role text check (role in ('user', 'assistant')),
  content text,
  is_crisis boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. ROW LEVEL SECURITY (RLS)
-- Enable RLS
alter table profiles enable row level security;
alter table journal_entries enable row level security;
alter table chats enable row level security;

-- Policies for Profiles
create policy "Users can view own profile" on profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);
create policy "Users can insert own profile" on profiles for insert with check (auth.uid() = id);

-- Policies for Journal
create policy "Users can view own journal" on journal_entries for select using (auth.uid() = user_id);
create policy "Users can insert own journal" on journal_entries for insert with check (auth.uid() = user_id);
create policy "Users can delete own journal" on journal_entries for delete using (auth.uid() = user_id);

-- Policies for Chats
create policy "Users can view own chats" on chats for select using (auth.uid() = user_id);
create policy "Users can insert own chats" on chats for insert with check (auth.uid() = user_id);

-- 4. AUTOMATION & TRIGGERS

-- Function to handle new user signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, name, streak_count)
  values (new.id, null, 0);
  return new;
end;
$$ language plpgsql security definer;

-- Trigger execution
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 5. STORAGE (Optional - mainly if we add profile pics later)
-- insert into storage.buckets (id, name) values ('avatars', 'avatars') ON CONFLICT DO NOTHING;
