-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Profiles table
create table profiles (
  id uuid references auth.users not null primary key,
  name text,
  streak_count int default 0,
  last_check_in timestamp with time zone,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Moods table
create table moods (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  mood_level int check (mood_level between 1 and 5),
  note text,
  sentiment_score int,
  ai_tags text[],
  ai_response text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Chats table
create table chats (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  role text check (role in ('user', 'assistant')),
  content text,
  is_crisis boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Row Level Security
alter table profiles enable row level security;
alter table moods enable row level security;
alter table chats enable row level security;

-- Policies
create policy "Users can view own profile" on profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);
create policy "Users can insert own profile" on profiles for insert with check (auth.uid() = id);

create policy "Users can view own moods" on moods for select using (auth.uid() = user_id);
create policy "Users can insert own moods" on moods for insert with check (auth.uid() = user_id);
create policy "Users can delete own moods" on moods for delete using (auth.uid() = user_id);

create policy "Users can view own chats" on chats for select using (auth.uid() = user_id);
create policy "Users can insert own chats" on chats for insert with check (auth.uid() = user_id);
